### ISSUE TITLE
Как жить без миксин?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [bevis-ui/docs#11]
Допустим у меня есть блок кнопка, она замечательная, красивая, с богатым внутренним миром.
И я хочу вставить в страницу две такие кнопки но они будут выполнять совершенно разные задачи.
Будут ли эти кнопки одним и тем-же блоком?
Или это разные блоки с разными именами?

В БЭМ можно создать блок и примиксовать к нему другой и все стили и поведения от этого блока будут у текущего. 
Но при этом блок также имеет свой внутренний мир и свое имя.

Как в bevis создавать новые, похожие блоки не копируя css и часть js от уже существующих похожих блоков?

**Comment by mdevils** [comment]
> Элемент Tree__item должен перехватить это событие и проставить состояние _open для элемента Tree__list который находится внутри него.

В BEViS элементы сами ничего делать не могут. Но могут делать блоки с помощью элементов. В твоем случае стоит сделать новый блок `TreeItem`, внутри него слушать `toggled` на блоке `Toggle` и генерировать свое событие, которое уже поймает `Tree`. Можно и элементами все реализовать через live-события, но будет выглядеть менее красиво.

**Comment by makishvili** [comment]
Егор, я могу закрыть таску или продолжим беседу?

**Comment by egor-a-trubnikov-panov** [comment]
Можно закрывать. Спасибо!
