### ISSUE TITLE
Есть ли (будет?) возможность быстрой компиляции проекта в статику?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [bevis-ui/docs#15]
Есть ли (будет?) возможность быстрой компиляции проекта в статику?
Чтобы получить html-ки c правильными путями до js-ок и css-ок в удобном для выкладки виде.

**Comment by makishvili** [comment]
Генерацию html мы уже делали в репозитории bevis-blog. После `make` в корне проекта появится папка `static` со статическими `html`-файлами.

Правда там всё сшито-перешито специально для ведения блога на `markdown`, отдельного отчуждаемого инструмента для генерации статики не делали. А хотелось бы, это точно :)

**Comment by egor-a-trubnikov-panov** [comment]
Багодарю :)

**Comment by makishvili** [comment]
Вы подсмотрели, вам это пригодится?
Или пока отложили это дело? :)

**Comment by egor-a-trubnikov-panov** [comment]
подсмотрел и пока отложил :)
