### ISSUE TITLE
Можно ли указать, какие шаблоны блоков нужно тянуть на front-end а какие оставить?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [bevis-ui/docs#17]
Сейчас все шаблоны склеиваются в один js файл вместе с логикой блоков что делает его достаточно тяжелым для загрузки на клиента. 
Зачастую на клиенте не нужны все шаблоны блоков. 
Нужны только те которые будут рендерится на нем.
Есть ли возможность как-то управлять тем какие шаблоны тянуть на front-end а какие нет?

**Comment by dracowf** [comment]
Возможно вам пригодится:
https://github.com/bevis-ui/docs/blob/master/how-to-make/yblock.md#Живая-инициализация-блоков

**Comment by makishvili** [comment]
Нет, Саша, Егор не об этом. Егор о том, что в собранном страничном файле находятся все-все bt-шаблоны, даже те, которые отработали на сервере и никогда на клиенте не запустятся.

Я не знаю ответа.

/cc @mdevils Марат, подскажи, пожалуйста. Есть ли такая возможность?

**Comment by mdevils** [comment]
Нет, к сожалению такой возможности нет. Предполагается, что приложение целиком или практически целиком клиентское и построение происходит, в основном, на клиенте.

**Comment by makishvili** [comment]
Егор, закрываем таску? Грустим вместе с вами и закрываем. Да? ;)
