### ISSUE TITLE
А практикум мы обязательно допишем ;)

### ISSUE THREAD

**Issue by pahaz** [bevis-ui/docs#18]
- Как написать js-поведение для блока? [*]
 - Как настроить локализацию? [*]

Расскажите про статус проекта? 

![image](https://cloud.githubusercontent.com/assets/1394025/6865880/622e6100-d494-11e4-98d4-961cb218d6a0.png)

**Comment by makishvili** [comment]
Оказалось, наше членство в группе было приватным. Изменил своё состояние.
Хотите, добавлю и вас в группу? :)

Про js-поведение есть начатый черновик. 
Про локализацию нет ничего.

Про статус скажу просто — мне надо сесть и дописать всё, что обещал :)

**Comment by pahaz** [comment]
> Хотите, добавлю и вас в группу? :)

Мне кажется, что я пока не внес столь существенный вклад в развитие проекта :)

**Comment by makishvili** [comment]
Js-поведение описал. Начинаю описывать локализацию. Если будут вопросы или найдёте (обязательно найдёте!) неточности, пишите :)
