### ISSUE TITLE
Нашёл небольшую нестыковку

### ISSUE THREAD

**Issue by DracoWF** [bevis-ui/docs#22]
К имени блока вместо конкретного вью добавьте маску *:

Было:

module.exports = function (bt) {
    bt.match('input_large', function (ctx) {
        // ...
    });
};
Стало:

module.exports = function (bt) {
    bt.match('input*', function (ctx) {
        // ...
    });
};
Но при этом надо добавить маску ещё и к:

bt.match('input*__control', function (ctx) {
        // ...
    });
Без этого не подтягиваются стили =) И интересный баг с крестиком происходит :)

**Comment by DracoWF** [comment]
Ам... а когда ждать продолжения по JS и BT? :)

**Comment by makishvili** [comment]
Про маску  - спасибо, я упустил :(Исправлю.  А какой баг с крестиком? Вы о чём?12.07.2015, 21:02, "DracoWF" <notifications@github.com>:К имени блока вместо конкретного вью добавьте маску *:

Было:

module.exports = function (bt) {
    bt.match('input_large', function (ctx) {
        // ...
    });
};
Стало:

module.exports = function (bt) {
    bt.match('input*', function (ctx) {
        // ...
    });
};
Но при этом надо добавить маску ещё и к:

bt.match('input*__control', function (ctx) {
        // ...
    });
Без этого не подтягиваются стили =) И интересный баг с крестиком происходит :)

**Comment by DracoWF** [comment]
http://gyazo.com/71e9a5dce20fa55024a313ecca7fdf7f
Вот, если как раз без маски делать, то получается вот такой забавный эффект )

**Comment by makishvili** [comment]
Поправил документацию. Спасибо вам, Александр.
