### ISSUE TITLE
Пример в "Учебнике для новичков"

### ISSUE THREAD

**Issue by LeusMaximus** [bevis-ui/docs#23]
В  ["Учебнике для новичков"](https://github.com/bevis-ui/docs/blob/master/manual-for-beginner.md) есть такой пример http://prntscr.com/7sipd0
Если я правильно понял, на картинке в лого должен быть класс header__image ?

**Comment by makishvili** [comment]
Вы абсолютно правы, Максим. Спасибо вам.
Сейчас исправлю.

**Comment by makishvili** [comment]
Исправил.
