### ISSUE TITLE
Название input__control

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/docs#24]
После паузы, не сразу смог понять почему control =)

> А в терминах BEViS поле формы представлено элементом блока, и имя этому элементу — control.
> Перепишем методы:
```
getValue: function() {
    var control = this._findElement('control');
    return control.val();
},
setValue: function(value) {
    var control = this._findElement('control');
    control.val(value);
}
```

Возможно, text-field или что-то попроще? :)

**Comment by makishvili** [comment]
Ммм, понял трудность. Добавлю пояснение/напоминание. Спасибо, Саша.

**Comment by dracowf** [comment]
Супер! :)
