### ISSUE TITLE
Может неочевидный переход?

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/docs#25]
От
>
```
var clear = this._findElement('clear');
var control = this._findElement('control');
```

К
 >
```
this._clear = this._findElement('clear');
this._control = this._findElement('control');
```

Объяснить =)

**Comment by makishvili** [comment]
А вы это без объяснений поняли? Честно скажите :)

**Comment by makishvili** [comment]
Кстати, как вам этот материал? Возникает ли понимание, как программировать на yblock?

**Comment by dracowf** [comment]
Я так давно не прогал... Ну есть поле класса, которое задаётся перменной, к которой мы потом будем обращаться через Класс.перменная. А здесь внутри класса мы объявляем this(Класс).перменная, т.е. тоже самое, но сразу в классе. Всё же не до конца ясно/понятно)

**Comment by dracowf** [comment]
Без громких слов - вернул работу и желание учиться) Скажем так, ничего другое не радовало, это пришло ещё со знакомства с ООП, а сейчас модель декларативного объявления, а уже потом кодинга вернула веру) Сумбурно объяснил. =-) Ну а документация на Yblock хорошая, пока всё понятно)

**Comment by makishvili** [comment]
Про переменные я понял, Саш — опишу в документации этот моменте подробнее, прокомментирую рефакторинг полей класса, чтобы читатель не терялся.

А про вашу веру и желание учиться я немного не понял :)

**Comment by dracowf** [comment]
Скажем так, я давно к кодингу не подступался, ещё в институте перестал программировать со второго где-то курса, а до этого всё было на отлично :) Вот сейчас вернулся к кодингу, но т.к. большую часть времени проводил в изучении UX/UI понял, что можно бы и пооживлять эти мокапы здесь и ШРИ появилась и тут же появился Юрий Ветров, который навёл в материалах на БЭМ, а после этого вышел через презентацию одного из ваших коллег на BEViS и понял, что вот оно! :)
Я искренне признателен за материал =)
