### ISSUE TITLE
Битые ссылки в документации

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/docs#27]
Сначала ещё раз спасибо =) Очень большое за то, что могу учиться по вашим урокам.

Теперь немного того, что полетело в процессе вёрстки.
**Битые ссылки:**
Здесь: https://github.com/bevis-ui/docs/blob/master/how-to-make/css.md в конце.
> Вот, что должно было у вас получиться.

https://github.com/bevis-ui/bevis-stub/tree/input-with-styles/blocks/input

И здесь: https://github.com/bevis-ui/docs/blob/master/how-to-make/yblock.md
> унаследован от YBlock, а тот в свою очередь унаследовал его от класса EventEmitter. Документацию к этому классу и к его методам для работы с событиями можно прочитать здесь.

https://github%20.com/bevis-ui/bevis-stub/blob/master/core/event-emitter/event-emitter.js

**Вопросы:** =)
*1*
>_bindTo
Первый параметр — элемент или блок, на котором слушаем событие.

Никак не получается передать чистый блок, можно узнать каким образом это сделать? :)

*2*
Есть 3 одинаковых блока input. Допускает ли BEViS возможно по наведению на один из блоков, раскрасить все другие? Как ни стараюсь никак не могу понять, как это сделать.
```
this._bindTo(this._control, 'mouseover', this.hover);
this._bindTo(this._control, 'mouseout', this.nothover);

hover: function () {
                this._setState('hover');
                *МАГИЯ*
                this.emit('hover-success');
            },

            nothover: function () {
                this._removeState('hover');
```

Со вторым вопросом разобрался:
```
hover: function () {
          $('.' + ClassName.getBlockName()).addClass('_hover');
},

nothover: function () {
          $('.' + ClassName.getBlockName()).removeClass('_hover');
},
```

Ура! Разобрался с первым))), покопавшись в JSDoc'е =)

```
@example
         * var View = inherit(YBlock, {
         *     __constructor: function (model) {
         *         this.__base();
         *
         *         var hide = this._findElement('hide');
         *         this._bindTo(hide, 'click', this._onHideClick);
         *
         *         this._bindTo(model, 'change-attr', this._onAttrChange);
         *     }
         * });
```
Надо в конструктор передавать перменную =)

**Comment by makishvili** [comment]
Битые ссылки исправлю, спасибо.

По первому вопросу. Если ваше решение работает - отлично, пусть работает. 

Но мне оно кажется неправильным идеологически. В идеале Класс Инпут должен думать только о себе. Влиять как-то на другие блоки он не должен. Поэтому я бы продолжил ваше первое решение:

Пусть по маузоверу вызывается не сразу `hover`, а специальный обработчик.
```javascript
__constructor: function () {
    //...
    this._bindTo(this._control, 'mouseover', this._onControlHovered);
    //...
},

_onControlHovered: function () {
    this.hover()
    this.emit('hover-success');
},

hover: function () {
    this._setState('hover');
},
```

А в том Классе, из которого `Input` был создан (в моих примерах это класс `Form`) я бы все инпуты сохранил в некий массив и работал бы с ним так
`Form`
```javascript
__constructor: function () {
    //...
    this._inputs = {
        new Input({btjson-параметры для первого инпута});
        new Input({btjson-параметры для второго инпута});
        new Input({btjson-параметры для третьго инпута});
    };

    this._inputs.forEach(function (input){
        input.on('hover-success', this._hoverAll, this);
    }.bind(this));
   //...
},

/**
 * Подсвечивает все инпуты
 */
_hoverAll: function () {
    this._inputs.forEach(function (input){
        input.hover();
    }.bind(this));
}
```

И этот код можно улучшить, но идея именно такая - все операции над инпутами должен производить из другого объекта, из некоего Контроллера.

**Comment by makishvili** [comment]
Про второй вопрос. Интересный пример вы нашли. Я привык в конструктор передавать параметры в виде объекта 
```javascript
new View({
    model: new SomeThing()
});
```

И тогда принимать параметры чуть иначе:
```javascript
var View = inherit(YBlock, {
         __constructor: function (params) {
              this.__base();

              this._bindTo(params.model, 'change-attr', this._onAttrChange);
         }
 });
```

Так оно лучше расширяется, можно в любой момент добавить новые параметры, не ломая код.

**Comment by dracowf** [comment]
А в данном случае сам блок это будет params без .model?

**Comment by makishvili** [comment]
Саша, я не понял ваш вопрос.  Чуть разверните его, пожалуйста :)

**Comment by dracowf** [comment]
Ну т.е. мы принимаем params в конструктор.
При создании объекта класса View мы говорим, что один из параметров будет model: new Something.

Возвращаясь к hover'у:
```
var View = inherit(YBlock, {
         __constructor: function (params) {
              this.__base();

              this._bindTo(params.model, 'mouseover', this._onControlHovered);
         }
 });
```
В данном случае он будет работать только по наведению на model (вот такой у нас model :))
```
var View = inherit(YBlock, {
         __constructor: function (params) {
              this.__base();

              this._bindTo(params, 'mouseover', this._onControlHovered);
         }
 });
```
А здесь по наведению на блок, т.к. params это и есть весь блок, я правильно понимаю? Или всё же блок это params.model или я вообще всё попутал?

**Comment by makishvili** [comment]
Мы тут с вами намешали примеры из `JSDoc` и примеры из `yblock.md`, я запутался, если честно :)

Опишите мне, пожалуйста, задачу - для чего вам нужно в конструктор какого-то блока передавать другой блок. Может так я "распутаюсь" :)

**Comment by dracowf** [comment]
Мне нужно просто для метода _bindTo слушать событие на текущем блоке, а не его элементах.
Для этого в метод _bindTo необходимо первым аргументом передать сам блок.
```
this._bindTo(СамБлок, 'mouseover', this._onControlHovered);
```
Правильно ли я понимаю, что, если мы записываем вот так:
```
__constructor: function (params)
```
, то params это и есть представление Самого Блока...
А обращения вида params**.какое-то_поле** это уже данные, к которым мы можем обращаться, но не блок целиком? :)

**Comment by makishvili** [comment]
Кажется, вам должно помочь `this` :)

```javascript
this._bindTo(this, 'mouseover', this._onControlHovered);
```

Работает?

**Comment by dracowf** [comment]
Вот он как раз и не работал =( Пойду ещё раз попробую, но вываливал ошибку, с которой я так и намучился =).

**Comment by dracowf** [comment]
Ошибку сейчас не отлавливаю в консоле, но не работает =)

**Comment by makishvili** [comment]
я сам попробую и вам сообщу ;)

**Comment by dracowf** [comment]
Хорошо =)

**Comment by makishvili** [comment]
Так должно работать.
```javascript
this._bindTo(this.getDomNode(), 'mouseover', this._onControlHovered);
```

**Comment by makishvili** [comment]
Саша, мы со всем разобрались, будем закрывать или остались вопросы по таске?

**Comment by dracowf** [comment]
Отлично! =) Всё работает =)
