### ISSUE TITLE
Описать, как Form.render рендерит блок на странице

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/docs#28]
Хотелось бы больше услышать о функции _render() вот здесь:
>А теперь мы налету будем генерить input!
Открываем blocks/form/form.js и пишем:

>1. Мы удалили метод render(). Он не нужен.

Слишком быстро добавили и убрали :)
И ещё понравился *правильный* способ создания элементов: _createElement =)

**Comment by makishvili** [comment]
Лучше новые issues создавать - по одному на каждый вопрос :)

О функции `render`  напишу чуть подробнее :)

**Comment by makishvili** [comment]
Закрою, когда опишу момент про render, хорошо?

**Comment by dracowf** [comment]
Скорее лучше бы рассказать, что он конкретно делает, а почему его потом перенесли в Input это ясно =)))
