### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/docs#30]
Бивисный слэк, он существует :)?
https://bevis.slack.com уже существует...

**Comment by makishvili** [comment]
Нет, мы не заводили slack. Это точно не наш

**Comment by dracowf** [comment]
Не планируется? :)

**Comment by makishvili** [comment]
А разве нужно? В этом проекте нет такой активности, чтобы заводить слэк. Собственно, здесь нет вообще никакой активности, если вы заметили. Только вы, Саша, и Пахаз Блинов интересуются. И то, Пахаз, кажется, уже потерял терпение, пока я опишу проект. Я его понимаю :)

**Comment by dracowf** [comment]
Возможно и нет нужды, но, надеюсь в будущем, когда сообщество разрастётся, появится :)

**Comment by makishvili** [comment]
Тогда первым делом заведём и вы станете в нём первым пользователем. Замётано? ;)

**Comment by makishvili** [comment]
Или давайте сделаем так. Заводите, Александр. Назовите его bevis-ui, чтобы одинаково с именем в гитхабе. И перенесём отвлеченные обсуждения туда. Есть у вас силы и желание это сделать?

**Comment by dracowf** [comment]
Отлично! Даже и не надеялся =)

**Comment by dracowf** [comment]
Кидаю инвайт :)

**Comment by makishvili** [comment]
я вроде как вошёл туда :)

**Comment by dracowf** [comment]
Проверочка :)

**Comment by makishvili** [comment]
Отлично. 
bevis-ui.slack.com

**Comment by jt3k** [comment]
мейби лучше не проприетарный слак а  православный джаббер на публичном сервере ?

**Comment by dracowf** [comment]
А чем бедняга Слэк не угодил, вроде как не АЭС проектируем =)

**Comment by VovanR** [comment]
https://gitter.im/ лучше

**Comment by jt3k** [comment]
слэк загнётся -- чат пропадёт.
гиттер тоже туда же.

Свободные программные продукты более надёжны.
